### ISSUE TITLE
Entities suddenly unavailable, reinstall not resolving.

### ISSUE THREAD

**Issue by Paulholloway** [twhittock/eo_mini#6]
## Version of the custom_component
38f9569

## Configuration
NA - logged in as per instructions

## Describe the bug
Having used this integration for months with no issues, all entities suddenly became unavailable around 2am.  
No improvements were noticed on reloading the entity, restarting HA, removing the entity and HACS integration, and reinstalling.  Despite being able to log in OK via the UI, now no entities are shown.  iOS EO app works fine, so presume that the problem is not with EO?

Home Assistant 2023.8.0
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

## Log Entries
2023-08-04 11:42:31.423 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration eo_mini which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
...
2023-08-04 11:43:07.134 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform eo_mini
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial'
2023-08-04 11:43:07.644 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up eo_mini platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial'
2023-08-04 11:43:07.736 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform eo_mini
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial'
2023-08-04 11:43:07.741 ERROR (MainThread) [homeassistant.components.switch] Error while setting up eo_mini platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by twhittock** [comment]
Did this happen after updating to 2023.8? I've not done it yet... I'll see if I can have a look this weekend.

**Comment by Paulholloway** [comment]
I think so, I have an automation that runs at 2am to install these updates (the first time anything has broken after one to be fair) so that would relate.  I'd love to confirm this by rolling back to an earlier version but can't be doing with the faff.  Hopefully it's a simple fix - let me know if you've any suggestions.  
Thanks for your help - more than happy to buy you a coffee or something for your time; the integration is really helpful!

**Comment by twhittock-disguise** [comment]
Thanks.

It was caused by some change to the way HA wants devices to be registered - it seems a few other integrations had the same thing. No-one caught it because I don't check every beta build before release, and we don't have many users of the integration.

I've pushed the fix in 87c314d.

Thanks for letting me know.

**Comment by twhittock** [comment]
Thanks for the update, it seems other integrations had similar issues - I don't check the beta builds, so it slipped through - 87c314d fixes the issue.

Thanks for the encouragement and helpful report.
